development: &default
  adapter: postgresql
  database: dolores-landingham-bot_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>
  timeout: 5000

test:
  <<: *default
  database: dolores-landingham-bot_test

production: &default
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>

staging: *default
